# Etapa 1: build/publish de la app
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Copiamos el csproj y restauramos dependencias
COPY *.csproj ./
RUN dotnet restore

# Copiamos el resto del código y publicamos
COPY . ./
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

# Etapa 2: imagen final ligera para ejecutar
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app

# Copiamos lo publicado
COPY --from=build /app/publish .

# La API escuchará en el puerto 8080 dentro del contenedor
ENV ASPNETCORE_URLS=http://0.0.0.0:8080
EXPOSE 8080

# IMPORTANTE: el DLL debe coincidir con el nombre de tu proyecto (Security)
ENTRYPOINT ["dotnet", "Security.dll"]
