// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Security.Data;

#nullable disable

namespace Security.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251128044833_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EjercicioRutina", b =>
                {
                    b.Property<Guid>("EjerciciosId")
                        .HasColumnType("uuid");

                    b.Property<int>("RutinasId")
                        .HasColumnType("integer");

                    b.HasKey("EjerciciosId", "RutinasId");

                    b.HasIndex("RutinasId");

                    b.ToTable("EjercicioRutina");
                });

            modelBuilder.Entity("Security.Entities.Rutina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreadorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NivelObjetivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreadorId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("Security.Models.Ejercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Equipamiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("Security.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentJwtId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RefreshTokenRevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RutinaId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RutinaId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Security.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("Altura")
                        .HasColumnType("double precision");

                    b.Property<int?>("AniosExperiencia")
                        .HasColumnType("integer");

                    b.Property<string>("Certificacion")
                        .HasColumnType("text");

                    b.Property<double>("Edad")
                        .HasColumnType("double precision");

                    b.Property<string>("Especialidad")
                        .HasColumnType("text");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Peso")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("EjercicioRutina", b =>
                {
                    b.HasOne("Security.Models.Ejercicio", null)
                        .WithMany()
                        .HasForeignKey("EjerciciosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Security.Entities.Rutina", null)
                        .WithMany()
                        .HasForeignKey("RutinasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Security.Entities.Rutina", b =>
                {
                    b.HasOne("Security.Models.User", "Creador")
                        .WithMany("RutinasCreadas")
                        .HasForeignKey("CreadorId");

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("Security.Models.User", b =>
                {
                    b.HasOne("Security.Entities.Rutina", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("RutinaId");
                });

            modelBuilder.Entity("Security.Models.UserProfile", b =>
                {
                    b.HasOne("Security.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Security.Models.UserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Security.Entities.Rutina", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Security.Models.User", b =>
                {
                    b.Navigation("Profile");

                    b.Navigation("RutinasCreadas");
                });
#pragma warning restore 612, 618
        }
    }
}
